// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnMuhasebeApp.Infrastructure.Context;

#nullable disable

namespace OnMuhasebeApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("OnMuhasebeApp.Core.Entities.Cari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cariler", (string)null);
                });

            modelBuilder.Entity("OnMuhasebeApp.Core.Entities.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CariId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FaturaTuru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.ToTable("Faturalar", (string)null);
                });

            modelBuilder.Entity("OnMuhasebeApp.Core.Entities.FaturaSatiri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("TEXT");

                    b.Property<int>("FaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SatirToplami")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.ToTable("FaturaSatirlari", (string)null);
                });

            modelBuilder.Entity("OnMuhasebeApp.Core.Entities.KasaIslemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CariId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.ToTable("KasaIslemleri", (string)null);
                });

            modelBuilder.Entity("OnMuhasebeApp.Core.Entities.Fatura", b =>
                {
                    b.HasOne("OnMuhasebeApp.Core.Entities.Cari", "Cari")
                        .WithMany("Faturalar")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("OnMuhasebeApp.Core.Entities.FaturaSatiri", b =>
                {
                    b.HasOne("OnMuhasebeApp.Core.Entities.Fatura", "Fatura")
                        .WithMany("FaturaSatirlari")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("OnMuhasebeApp.Core.Entities.KasaIslemi", b =>
                {
                    b.HasOne("OnMuhasebeApp.Core.Entities.Cari", "Cari")
                        .WithMany("KasaIslemleri")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("OnMuhasebeApp.Core.Entities.Cari", b =>
                {
                    b.Navigation("Faturalar");

                    b.Navigation("KasaIslemleri");
                });

            modelBuilder.Entity("OnMuhasebeApp.Core.Entities.Fatura", b =>
                {
                    b.Navigation("FaturaSatirlari");
                });
#pragma warning restore 612, 618
        }
    }
}
